// 南部档案馆 · 闯关剧本（10 关，悬疑探案风）
// 每关支持两种底图模式：
// 1. 双图模式：提供 imageA + imageB 两张成品图，diffs 只负责点击区域
// 2. 单图模式：仅 imageA（或 painterId 占位图）+ diffs 程序化生成 B 图

const W = 720;
const H = 540;

module.exports = {
  chapterId: 'south_archive',
  chapterTitle: '难不挡案',
  chapterIntro: '故事设定在民国初立的特殊时期，主线围绕一名档案馆青年探员远赴南洋群岛，\n调查一系列诡异海域命案展开。',
  imageSize: { w: W, h: H },
  levels: [
    {
      levelId: 'archive_01',
      story: '峇来举行了一场传统的南洋婚礼，新娘陪嫁中暗藏着一尊会发声的“峇来神像”（及蛇形泥雕）。婚后不久，新郎全家离奇惨死在盐碱湖畔，死状呈现出疯狂挖掘湖床的诡异姿态。',
      painterId: 'archive_01',
      imageA: 'levels/images/archive_01.jpeg',
      imageB: 'levels/images/archive_01_diff.jpeg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 120,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 374, y: 334, r: 12, hitR: 28, desc: '眼下泪痣' },
        { id: 'd2', x: 455, y: 523, r: 22, hitR: 36, desc: '下巴胡须' },
        { id: 'd3', x: 360, y: 658, r: 16, hitR: 32, desc: '衣领纽扣' },
      ],
      starThresholds: { 3: 50, 2: 90, 1: 120 },
    },
    {
      levelId: 'archive_02',
      story: '走廊尽头有人影一闪。你确认过钥匙是你这把。',
      painterId: 'archive_02',
      imageA: 'levels/images/archive_02.jpg',
      imageB: 'levels/images/archive_02_diff.jpeg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 90,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 820, y: 372, r: 18, hitR: 34, desc: '右手手腕手表' },
        { id: 'd2', x: 769, y: 488, r: 16, hitR: 32, desc: '右手手指戒指' },
        { id: 'd3', x: 171, y: 417, r: 16, hitR: 32, desc: '左手小花' },
        { id: 'd4', x: 70, y: 379, r: 16, hitR: 32, desc: '左手手腕处小花' },
      ],
      starThresholds: { 3: 40, 2: 65, 1: 90 },
    },
    {
      levelId: 'archive_03',
      story: '台灯亮着，像是有人刚走。',
      painterId: 'archive_03',
      imageA: 'levels/images/archive_03.jpg',
      imageB: 'levels/images/archive_03_diff.png',
      imageSize: { w: 900, h: 675 },
      timeLimit: 90,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 151, y: 482, r: 20, hitR: 36, desc: '袋子上的小红花' },
        { id: 'd2', x: 122, y: 150, r: 20, hitR: 36, desc: '干草上的绿叶' },
        { id: 'd3', x: 551, y: 291, r: 20, hitR: 36, desc: '右耳朵上的耳钉' },
        { id: 'd4', x: 472, y: 486, r: 20, hitR: 36, desc: '领口处的纽扣' },
        { id: 'd5', x: 532, y: 613, r: 20, hitR: 36, desc: '手腕处的疤痕' },
        { id: 'd6', x: 481, y: 549, r: 20, hitR: 36, desc: '胸口纽扣下边的衬衣花纹' }
      ],
      starThresholds: { 3: 35, 2: 60, 1: 90 },
    },
    {
      levelId: 'archive_04',
      story: '台阶底端的光不是你点的。',
      painterId: 'archive_04',
      imageA: 'levels/images/archive_04.jpeg',
      imageB: 'levels/images/archive_04_diff.jpg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 90,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 92, y: 325, r: 20, hitR: 36, desc: '海侠左胳膊多了一处臂章' },
        { id: 'd2', x: 231, y: 253, r: 20, hitR: 36, desc: '海楼项链吊坠颜色' },
        { id: 'd3', x: 466, y: 361, r: 20, hitR: 36, desc: '海侠项链吊坠颜色' },
        { id: 'd4', x: 683, y: 282, r: 20, hitR: 36, desc: '张海琪耳坠颜色' },
        { id: 'd5', x: 691, y: 467, r: 20, hitR: 36, desc: '张海琪手表和手链' },
        { id: 'd6', x: 843, y: 287, r: 20, hitR: 36, desc: '张海琪右后方箱子花纹' }
      ],
      starThresholds: { 3: 40, 2: 70, 1: 100 },
    },
    {
      levelId: 'archive_05',
      story: '茶楼街口人来人往。旗袍女子的耳坠、相机挂绳、灯笼纹理……每一处细节都可能藏着线索。',
      painterId: 'archive_05',
      imageA: 'levels/images/archive_05.jpeg',
      imageB: 'levels/images/archive_05_diff.jpeg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 100,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 637, y: 326, r: 20, hitR: 36, desc: '耳钉的颜色' },
        { id: 'd2', x: 329, y: 536, r: 20, hitR: 36, desc: '相机颜色' },
        { id: 'd3', x: 345, y: 99, r: 20, hitR: 36, desc: '茶楼缺少楼' },
        { id: 'd4', x: 827, y: 96, r: 20, hitR: 36, desc: '帽子颜色' },
        { id: 'd5', x: 878, y: 446, r: 20, hitR: 36, desc: '花朵颜色' },
        { id: 'd6', x: 214, y: 19, r: 20, hitR: 36, desc: '灯笼颜色' }
      ],
      starThresholds: { 3: 45, 2: 75, 1: 100 },
    },
    {
      levelId: 'archive_06',
      story: '空椅子排得整齐，唯有一盏灯灭了。',
      painterId: 'archive_06',
      imageA: 'levels/images/archive_06.jpeg',
      imageB: 'levels/images/archive_06_diff.jpg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 100,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 124, y: 456, r: 20, hitR: 36, desc: '油灯颜色' },
        { id: 'd2', x: 32, y: 328, r: 20, hitR: 36, desc: '布袋数量' },
        { id: 'd3', x: 196, y: 638, r: 20, hitR: 36, desc: '茶壶颜色' },
        { id: 'd4', x: 667, y: 410, r: 20, hitR: 36, desc: '胸口新增一支钢笔' },
        { id: 'd5', x: 743, y: 654, r: 20, hitR: 36, desc: '相机旁边新增一个小茶杯' },
        { id: 'd6', x: 220, y: 140, r: 20, hitR: 36, desc: '木牌上的文字' },
        { id: 'd7', x: 396, y: 606, r: 20, hitR: 40, desc: '报纸上文字标题大小' }
      ],
      starThresholds: { 3: 45, 2: 75, 1: 100 },
    },
    // {
    //   levelId: 'archive_07',
    //   title: '第七关 · 储藏间',
    //   story: '木箱钉牢。最里那只，钉了三遍。',
    //   painterId: 'archive_07',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 110, y: 400, r: 40, color: '#3a2a4a', desc: '左箱颜色' },
    //     { id: 'd2', type: 'overlay', x: 360, y: 400, r: 16, icon: 'cross', desc: '中箱上的封条', shape: 'cross' },
    //     { id: 'd3', type: 'overlay', x: 560, y: 380, r: 10, icon: 'key', desc: '右箱旁钥匙' },
    //     { id: 'd4', type: 'recolor', x: 660, y: 460, r: 16, color: '#3a3a3a', desc: '油灯熄灭' },
    //     { id: 'd5', type: 'overlay', x: 100, y: 50, r: 24, icon: 'cobweb', desc: '麻布上蛛网' },
    //     { id: 'd6', type: 'shape', x: 460, y: 480, r: 8, shape: 'cross', color: '#8a1a1a', desc: '地上红十字' },
    //   ],
    //   starThresholds: { 3: 45, 2: 75, 1: 100 },
    // },
    // {
    //   levelId: 'archive_08',
    //   title: '第八关 · 雨中屋顶',
    //   story: '雨砸下来。对面屋脊的人没动。',
    //   painterId: 'archive_08',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 620, y: 80, r: 30, color: '#8a3a2a', desc: '月亮变红' },
    //     { id: 'd2', type: 'patch', x: 510, y: 232, r: 14, sampleFrom: { x: 160, y: 280 }, desc: '人影消失' },
    //     { id: 'd3', type: 'shape', x: 360, y: 180, r: 20, shape: 'cross', color: '#c0a050', desc: '远空闪电' },
    //     { id: 'd4', type: 'overlay', x: 90, y: 360, r: 18, icon: 'cobweb', desc: '屋檐蛛网' },
    //     { id: 'd5', type: 'recolor', x: 340, y: 200, r: 22, color: '#1a1a1a', desc: '烟囱变高' },
    //     { id: 'd6', type: 'overlay', x: 580, y: 460, r: 10, icon: 'bloodstain', desc: '屋顶血迹' },
    //   ],
    //   starThresholds: { 3: 45, 2: 75, 1: 100 },
    // },
    // {
    //   levelId: 'archive_09',
    //   title: '第九关 · 钟楼',
    //   story: '钟停在十一点四十。馆长信里写过这个时间。',
    //   painterId: 'archive_09',
    //   imageA: '',
    //   timeLimit: 110,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 360, y: 270, r: 110, color: '#5a2a2a', blendAlpha: 0.5, desc: '钟面色' },
    //     { id: 'd2', type: 'mirror', x: 360, y: 270, r: 60, desc: '指针方向' },
    //     { id: 'd3', type: 'patch', x: 460, y: 200, r: 14, sampleFrom: { x: 460, y: 100 }, desc: '某个刻度消失' },
    //     { id: 'd4', type: 'overlay', x: 80, y: 460, r: 18, icon: 'key', desc: '齿轮上的钥匙' },
    //     { id: 'd5', type: 'recolor', x: 80, y: 460, r: 36, color: '#3a2a4a', desc: '齿轮变色' },
    //     { id: 'd6', type: 'overlay', x: 660, y: 60, r: 22, icon: 'eye', desc: '角落的眼睛' },
    //     { id: 'd7', type: 'shape', x: 360, y: 480, r: 10, shape: 'cross', color: '#c0a050', desc: '地上印记' },
    //   ],
    //   starThresholds: { 3: 50, 2: 80, 1: 110 },
    // },
    // {
    //   levelId: 'archive_10',
    //   title: '第十关 · 密室',
    //   story: '钥匙第二齿对应的门。书摊开在最后一页。',
    //   painterId: 'archive_10',
    //   imageA: '',
    //   timeLimit: 120,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 360, y: 60, r: 28, color: '#8a1a1a', desc: '顶部符号变红' },
    //     { id: 'd2', type: 'recolor', x: 360, y: 327, r: 18, color: '#3a2a5a', desc: '书皮变色' },
    //     { id: 'd3', type: 'patch', x: 290, y: 300, r: 18, sampleFrom: { x: 200, y: 360 }, desc: '左烛台消失' },
    //     { id: 'd4', type: 'overlay', x: 100, y: 460, r: 16, icon: 'envelope', desc: '地上信封' },
    //     { id: 'd5', type: 'overlay', x: 620, y: 100, r: 20, icon: 'eye', desc: '墙角的眼睛' },
    //     { id: 'd6', type: 'overlay', x: 540, y: 420, r: 12, icon: 'bloodstain', desc: '祭台血迹' },
    //     { id: 'd7', type: 'mirror', x: 360, y: 60, r: 24, desc: '符号镜像' },
    //     { id: 'd8', type: 'shape', x: 200, y: 460, r: 10, shape: 'cross', color: '#c0a050', desc: '地砖刻痕' },
    //   ],
    //   starThresholds: { 3: 60, 2: 90, 1: 120 },
    // },
  ],
};
