// 南部档案馆 · 闯关剧本（10 关，悬疑探案风）
// 每关支持两种底图模式：
// 1. 双图模式：提供 imageA + imageB 两张成品图，diffs 只负责点击区域
// 2. 单图模式：仅 imageA（或 painterId 占位图）+ diffs 程序化生成 B 图

const W = 720;
const H = 540;

module.exports = {
  chapterId: 'south_archive',
  chapterTitle: '南部档案馆',
  chapterIntro: '城南尽头那栋砖楼空了三十年。馆长失踪前留下一封信。\n你接过钥匙的那夜，雨没有停。',
  imageSize: { w: W, h: H },
  levels: [
    {
      levelId: 'archive_01',
      title: '第一夜 · 南洋峇来',
      story: '宴席灯火未熄，他站在门口，目光落在你身上。',
      painterId: 'archive_01',
      imageA: 'levels/images/archive_01.jpeg',
      imageB: 'levels/images/archive_01_comparison.jpeg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 120,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 374, y: 334, r: 12, hitR: 28, desc: '眼下泪痣' },
        { id: 'd2', x: 455, y: 523, r: 22, hitR: 36, desc: '下巴胡须' },
        { id: 'd3', x: 360, y: 658, r: 16, hitR: 32, desc: '衣领纽扣' },
      ],
      starThresholds: { 3: 50, 2: 90, 1: 120 },
    },
    {
      levelId: 'archive_02',
      title: '第二夜 · 长廊',
      story: '走廊尽头有人影一闪。你确认过钥匙是你这把。',
      painterId: 'archive_02',
      imageA: 'levels/images/archive_02.jpg',
      imageB: 'levels/images/archive_02_diff.jpeg',
      imageSize: { w: 900, h: 675 },
      timeLimit: 90,
      maxMisses: 3,
      debugCoords: false,
      diffs: [
        { id: 'd1', x: 820, y: 372, r: 18, hitR: 34, desc: '右手手腕手表' },
        { id: 'd2', x: 769, y: 488, r: 16, hitR: 32, desc: '右手手指戒指' },
        { id: 'd3', x: 171, y: 417, r: 16, hitR: 32, desc: '左手小花' },
        { id: 'd4', x: 70, y: 379, r: 16, hitR: 32, desc: '左手手腕处小花' },
      ],
      starThresholds: { 3: 40, 2: 65, 1: 90 },
    },
    // {
    //   levelId: 'archive_03',
    //   title: '第三夜 · 档案室',
    //   story: '台灯亮着，像是有人刚走。',
    //   painterId: 'archive_03',
    //   imageA: '',
    //   timeLimit: 90,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 180, y: 200, r: 30, color: '#5a3a8a', desc: '左书架某本' },
    //     { id: 'd2', type: 'recolor', x: 540, y: 240, r: 30, color: '#3a8a5a', desc: '右书架某本' },
    //     { id: 'd3', type: 'overlay', x: 360, y: 400, r: 14, icon: 'paper', desc: '桌上多一张纸' },
    //     { id: 'd4', type: 'patch', x: 410, y: 415, r: 16, sampleFrom: { x: 250, y: 415 }, desc: '消失的信封' },
    //     { id: 'd5', type: 'overlay', x: 290, y: 400, r: 6, icon: 'bloodstain', desc: '书页污点' },
    //     { id: 'd6', type: 'blur', x: 60, y: 480, r: 28, desc: '地面模糊脚印' },
    //   ],
    //   starThresholds: { 3: 35, 2: 60, 1: 90 },
    // },
    // {
    //   levelId: 'archive_04',
    //   title: '第四夜 · 楼梯井',
    //   story: '台阶底端的光不是你点的。',
    //   painterId: 'archive_04',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'overlay', x: 40, y: 40, r: 22, icon: 'cobweb', desc: '左上蛛网' },
    //     { id: 'd2', type: 'overlay', x: 360, y: 480, r: 16, icon: 'candle', desc: '台阶下的烛光' },
    //     { id: 'd3', type: 'recolor', x: 360, y: 280, r: 26, color: '#5a2a2a', desc: '某级台阶颜色' },
    //     { id: 'd4', type: 'overlay', x: 600, y: 360, r: 12, icon: 'key', desc: '台阶旁的钥匙' },
    //     { id: 'd5', type: 'patch', x: 360, y: 100, r: 24, sampleFrom: { x: 200, y: 80 }, desc: '扶手某段消失' },
    //     { id: 'd6', type: 'shape', x: 660, y: 60, r: 8, shape: 'cross', color: '#c0a050', desc: '墙角刻痕' },
    //   ],
    //   starThresholds: { 3: 40, 2: 70, 1: 100 },
    // },
    // {
    //   levelId: 'archive_05',
    //   title: '第五夜 · 馆长办公室',
    //   story: '钢笔还沾着墨。他到底何时离开？',
    //   painterId: 'archive_05',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 110, y: 100, r: 40, color: '#3a5a3a', desc: '左画框' },
    //     { id: 'd2', type: 'recolor', x: 610, y: 100, r: 40, color: '#5a2a3a', desc: '右画框' },
    //     { id: 'd3', type: 'overlay', x: 320, y: 360, r: 10, icon: 'bloodstain', desc: '纸上的污点' },
    //     { id: 'd4', type: 'patch', x: 130, y: 360, r: 14, sampleFrom: { x: 60, y: 360 }, desc: '墨水瓶消失' },
    //     { id: 'd5', type: 'overlay', x: 470, y: 380, r: 10, icon: 'key', desc: '桌角的钥匙' },
    //     { id: 'd6', type: 'mirror', x: 360, y: 320, r: 30, desc: '椅背图案翻转' },
    //     { id: 'd7', type: 'recolor', x: 660, y: 240, r: 24, color: '#3a3a3a', desc: '落地灯熄灭' },
    //   ],
    //   starThresholds: { 3: 45, 2: 75, 1: 100 },
    // },
    // {
    //   levelId: 'archive_06',
    //   title: '第六夜 · 阅览室',
    //   story: '空椅子排得整齐，唯有一盏灯灭了。',
    //   painterId: 'archive_06',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 80, y: 365, r: 22, color: '#ffd28c', blendAlpha: 0.6, desc: '左台灯亮起' },
    //     { id: 'd2', type: 'recolor', x: 640, y: 365, r: 22, color: '#3a3a3a', desc: '右台灯熄灭' },
    //     { id: 'd3', type: 'overlay', x: 360, y: 405, r: 14, icon: 'paper', desc: '桌上多一页' },
    //     { id: 'd4', type: 'patch', x: 120, y: 480, r: 22, sampleFrom: { x: 280, y: 480 }, desc: '左侧椅子消失' },
    //     { id: 'd5', type: 'overlay', x: 540, y: 460, r: 6, icon: 'bloodstain', desc: '椅垫痕迹' },
    //     { id: 'd6', type: 'recolor', x: 360, y: 395, r: 20, color: '#2a3a5a', desc: '某本书颜色' },
    //   ],
    //   starThresholds: { 3: 45, 2: 75, 1: 100 },
    // },
    // {
    //   levelId: 'archive_07',
    //   title: '第七夜 · 储藏间',
    //   story: '木箱钉牢。最里那只，钉了三遍。',
    //   painterId: 'archive_07',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 110, y: 400, r: 40, color: '#3a2a4a', desc: '左箱颜色' },
    //     { id: 'd2', type: 'overlay', x: 360, y: 400, r: 16, icon: 'cross', desc: '中箱上的封条', shape: 'cross' },
    //     { id: 'd3', type: 'overlay', x: 560, y: 380, r: 10, icon: 'key', desc: '右箱旁钥匙' },
    //     { id: 'd4', type: 'recolor', x: 660, y: 460, r: 16, color: '#3a3a3a', desc: '油灯熄灭' },
    //     { id: 'd5', type: 'overlay', x: 100, y: 50, r: 24, icon: 'cobweb', desc: '麻布上蛛网' },
    //     { id: 'd6', type: 'shape', x: 460, y: 480, r: 8, shape: 'cross', color: '#8a1a1a', desc: '地上红十字' },
    //   ],
    //   starThresholds: { 3: 45, 2: 75, 1: 100 },
    // },
    // {
    //   levelId: 'archive_08',
    //   title: '第八夜 · 雨中屋顶',
    //   story: '雨砸下来。对面屋脊的人没动。',
    //   painterId: 'archive_08',
    //   imageA: '',
    //   timeLimit: 100,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 620, y: 80, r: 30, color: '#8a3a2a', desc: '月亮变红' },
    //     { id: 'd2', type: 'patch', x: 510, y: 232, r: 14, sampleFrom: { x: 160, y: 280 }, desc: '人影消失' },
    //     { id: 'd3', type: 'shape', x: 360, y: 180, r: 20, shape: 'cross', color: '#c0a050', desc: '远空闪电' },
    //     { id: 'd4', type: 'overlay', x: 90, y: 360, r: 18, icon: 'cobweb', desc: '屋檐蛛网' },
    //     { id: 'd5', type: 'recolor', x: 340, y: 200, r: 22, color: '#1a1a1a', desc: '烟囱变高' },
    //     { id: 'd6', type: 'overlay', x: 580, y: 460, r: 10, icon: 'bloodstain', desc: '屋顶血迹' },
    //   ],
    //   starThresholds: { 3: 45, 2: 75, 1: 100 },
    // },
    // {
    //   levelId: 'archive_09',
    //   title: '第九夜 · 钟楼',
    //   story: '钟停在十一点四十。馆长信里写过这个时间。',
    //   painterId: 'archive_09',
    //   imageA: '',
    //   timeLimit: 110,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 360, y: 270, r: 110, color: '#5a2a2a', blendAlpha: 0.5, desc: '钟面色' },
    //     { id: 'd2', type: 'mirror', x: 360, y: 270, r: 60, desc: '指针方向' },
    //     { id: 'd3', type: 'patch', x: 460, y: 200, r: 14, sampleFrom: { x: 460, y: 100 }, desc: '某个刻度消失' },
    //     { id: 'd4', type: 'overlay', x: 80, y: 460, r: 18, icon: 'key', desc: '齿轮上的钥匙' },
    //     { id: 'd5', type: 'recolor', x: 80, y: 460, r: 36, color: '#3a2a4a', desc: '齿轮变色' },
    //     { id: 'd6', type: 'overlay', x: 660, y: 60, r: 22, icon: 'eye', desc: '角落的眼睛' },
    //     { id: 'd7', type: 'shape', x: 360, y: 480, r: 10, shape: 'cross', color: '#c0a050', desc: '地上印记' },
    //   ],
    //   starThresholds: { 3: 50, 2: 80, 1: 110 },
    // },
    // {
    //   levelId: 'archive_10',
    //   title: '第十夜 · 密室',
    //   story: '钥匙第二齿对应的门。书摊开在最后一页。',
    //   painterId: 'archive_10',
    //   imageA: '',
    //   timeLimit: 120,
    //   maxMisses: 3,
    //   diffs: [
    //     { id: 'd1', type: 'recolor', x: 360, y: 60, r: 28, color: '#8a1a1a', desc: '顶部符号变红' },
    //     { id: 'd2', type: 'recolor', x: 360, y: 327, r: 18, color: '#3a2a5a', desc: '书皮变色' },
    //     { id: 'd3', type: 'patch', x: 290, y: 300, r: 18, sampleFrom: { x: 200, y: 360 }, desc: '左烛台消失' },
    //     { id: 'd4', type: 'overlay', x: 100, y: 460, r: 16, icon: 'envelope', desc: '地上信封' },
    //     { id: 'd5', type: 'overlay', x: 620, y: 100, r: 20, icon: 'eye', desc: '墙角的眼睛' },
    //     { id: 'd6', type: 'overlay', x: 540, y: 420, r: 12, icon: 'bloodstain', desc: '祭台血迹' },
    //     { id: 'd7', type: 'mirror', x: 360, y: 60, r: 24, desc: '符号镜像' },
    //     { id: 'd8', type: 'shape', x: 200, y: 460, r: 10, shape: 'cross', color: '#c0a050', desc: '地砖刻痕' },
    //   ],
    //   starThresholds: { 3: 60, 2: 90, 1: 120 },
    // },
  ],
};
